### ISSUE TITLE
SCSS errors for Angular 15.x and 16.x - SassError: Undefined function.

### ISSUE THREAD

**Issue by JulienDuf** [Plabbee/angular-material-contrast-fix#2]
I'm testing your package with angular 15 and I have this scss error:

```
SassError: Undefined function.
  ╷
4 │     --mdc-filled-button-label-text-color: #{mat.get-theme-color($theme, $palette, default-contrast)};
  │                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules/angular-material-contrast-fix/components/_button.scss 4:45   -unelevated-button-variant()
  node_modules/angular-material-contrast-fix/components/_button.scss 42:13  button-theme()
  node_modules/angular-material-contrast-fix/components/_all.scss 7:5       all-component-themes()
```

I looked at the exported functions of `@angular/material` and the function `get-theme-color` is not available in Angular 15 and 16. It is a new implementation made in Angular 17.

**Comment by Plabbee** [comment]
Ahhhhh, hadn't realised it was a 17 introduction, explains why only recently saw it. Will sort this out this evening!

Plan is to:
 - Refactor a branch to use the old functions
 - Publish it to npm with 15.x, 16.x versions
 - Update the peer dependencies marked for 17.x
 - Create a separate demo app with the 15.x version

**Comment by JulienDuf** [comment]
Glad I could help!

I made this function, it seems to do the trick for my needs
```scss
@function _get-theme-color($theme, $palette, $contrast) {
    $config: map.get($theme, $palette);
    @return mat.get-color-from-palette($config, $contrast);
}

@mixin _unelevated-button-variant($theme, $palette) {
    --mdc-filled-button-label-text-color: #{_get-theme-color($theme, $palette, default-contrast)};
    --mat-filled-button-ripple-color: #{rgba(_get-theme-color($theme, $palette, default-contrast), 0.1)};
    --mat-filled-button-state-layer-color: #{_get-theme-color($theme, $palette, default-contrast)};
}
```
